# Site settings
title: Michael Bateman
email: info@michaelbateman.ca
description: > # Michael Bateman's project website
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://michaelbateman.ca" # the base hostname & protocol for your site

# Settings for the website
update: true # If you should be redirected to the update page
test: false # Beta update notice
chrome: true # Will redirect chrome users

# Social accounts
github: https://github.com/michael-bateman/michaelbateman.ca

# Build settings
markdown: kramdown